version: '3.8'

services:
  web-yavirac:
    image: web-yavirac:latest
    networks:
      - traefik-public
      - web_yairac      
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2096M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web-yavirac.entrypoints=http"
        - "traefik.http.routers.web-yavirac.rule=Host(`yavirac.edu.ec`)"
        - "traefik.http.middlewares.web-yavirac-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.web-yavirac.middlewares=web-yavirac-https-redirect"
        - "traefik.http.routers.web-yavirac-secure.entrypoints=https"
        - "traefik.http.routers.web-yavirac-secure.rule=Host(`yavirac.edu.ec`)"
        - "traefik.http.routers.web-yavirac-secure.tls=true"
        - "traefik.http.routers.web-yavirac-secure.tls.certresolver=http"
        - "traefik.http.routers.web-yavirac-secure.service=web-yavirac"
        - "traefik.http.services.web-yavirac.loadbalancer.server.port=2323"
        - "traefik.docker.network=traefik-public"
  mongo:
    image: mongo:5.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_web
      MONGO_INITDB_ROOT_PASSWORD: KinswomanFloristUpstageTaekwondoEngraverOveractDemeanorStraddleFlop
    networks:
      - web_yairac
    volumes:
      - mongo_data_web:/data/db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2096M

  express-mongo:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user_web
      ME_CONFIG_MONGODB_ADMINPASSWORD: KinswomanFloristUpstageTaekwondoEngraverOveractDemeanorStraddleFlop
      ME_CONFIG_MONGODB_URL: mongodb://user_web:KinswomanFloristUpstageTaekwondoEngraverOveractDemeanorStraddleFlop@mongo:27017/
    networks:
      - traefik-public
      - web_yairac
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mongo-express-prod.entrypoints=http"
        - "traefik.http.routers.mongo-express-prod.rule=Host(`mongo-express-prod.yavirac.edu.ec`)"
        - "traefik.http.middlewares.mongo-express-prod-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.mongo-express-prod.middlewares=mongo-express-prod-https-redirect"
        - "traefik.http.routers.mongo-express-prod-secure.entrypoints=https"
        - "traefik.http.routers.mongo-express-prod-secure.rule=Host(`mongo-express-prod.yavirac.edu.ec`)"
        - "traefik.http.routers.mongo-express-prod-secure.tls=true"
        - "traefik.http.routers.mongo-express-prod-secure.tls.certresolver=http"
        - "traefik.http.routers.mongo-express-prod-secure.service=express-mongo-prod"
        - "traefik.http.services.express-mongo-prod.loadbalancer.server.port=8081"
        - "traefik.docker.network=traefik-public"  

networks:
  traefik-public:
    external: true
  web_yairac:
    external: true

volumes:
  mongo_data_web:
    external: true
